Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "jenkins-master" do |master|
    master.vm.hostname = "jenkins-master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"         # 4 ГБ RAM
        vb.cpus = 6                # 6 CPU
        vb.customize ["modifyvm", :id, "--vram", "64"]  # 64 МБ 
        vb.customize ["modifyvm", :id, "--ioapic", "on"] 
    end
      master.vm.provision "shell", path: "provision_master.sh"
 
  end

  config.vm.define "jenkins-worker" do |worker|
    worker.vm.hostname = "jenkins-worker"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"     
        vb.cpus = 6              
        vb.customize ["modifyvm", :id, "--vram", "64"]  # 64 МБ
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    worker.vm.provision "shell", path: "provision_worker.sh"
  end
end
